import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import SinglePost from '../components/Post/SinglePost'
import Tag from '../components/Tag/Tag'
import { getAllTags, getPostsForTopPage } from '../lib/notionAPI'

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage(4)
  const allTags = await getAllTags()

  return {
    props: {
      fourPosts,
      allTags,
    },
    revalidate: 10,
  }
}

const Home = ({ fourPosts, allTags }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Sample Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <h1 className="text-5xl font-medium text-center mb-16">Sample Blog</h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {fourPosts.map(post => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={false}
              />
            </div>
          ))}
        </section>
        <Link
          href="/posts/page/1"
          className="block text-center font-medium text-white bg-sky-900 py-3 px-6 rounded-md mt-8 mb-10 mx-auto max-w-xs lg:max-w-none"
        >
          もっと見る
        </Link>
        <Tag tags={allTags} />
      </main>
    </div>
  )
}

export default Home
